# A pod that has 2 containers, the first container running as user ID 1000,
# the second as 2000, but both with the same file system group ID of 3000

apiVersion: v1
kind: Pod
metadata:
  name: practice-pod
  labels:
    app: web
spec:
  containers:
  - args:
    - client
    - name: container1
      image: kubegoldenguide/alpine-spin:1.0.0
      securityContext:
        runAsUser: 1000
        fsGroup: 3000
    - name: container2
      image: kubegoldenguide/alpine-spin:1.0.0
      securityContext:
        runAsUser: 2000
        fsGroup: 3000
