# Below is the yaml for creating secrets in Kubernetes 

apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
data:
  SECRET_DB_HOST: my_host
  SECRET_DB_PORT: my_port
  SECRET_DB_USERNAME: my_username
  SECRET_DB_PASSWORD: my_password

# and this is how you'd reference the secrets in a configMap 

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  database.properties: |
    database.url=jdbc:mysql://$(SECRET_DB_HOST):$(SECRET_DB_PORT)/mydatabase
    database.username=$(SECRET_DB_USERNAME)
    database.password=$(SECRET_DB_PASSWORD)